name: "Deploy Qwikskills Application 🚀"
description: "Deployment of SWA Application"

inputs:
  app-name:
    description: "App Name"
    required: true

  images:
    description: "Docker Image"
    required: true

  slot-name:
    desciption: "Slot Name"
    required: false
    
  AZURE_CREDENTIALS:
    description: "Azure Creds"
    required: true


runs:
  using: composite
  steps:
  
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.AZURE_CREDENTIALS }}
        
    - name: Deployment using Azure Action 🚀
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.app-name }}
        slot-name: ${{ inputs.slot-name }}
        images: ${{ inputs.images }}
