name: "Deploy to AKS 🚀"
description: "Deploying Backend Applications"

inputs:
  RG_NAME:
    description: "RG Name"
    required: true
  CLUSTER_NAME:
    description: "Cluster Name"
    required: true
  HELM_PATH:
    description: "Helm Path"
    required: true
  NAMESPACE:
    description: "AKS Namespace"
    required: true
  AZURE_CREDENTIALS:
    description: "Azure Creds"
    required: true
  ACR_ADDR:
    description: "ACR Address"
    required: true
  CHART_VERSION:
    description: "Chart Version"
    required: true
  ENV:
    description: "Deployment Env"
    required: true

runs:
  using: composite
  steps:
    - name: Deploying Application for ${{ inputs.NAMESPACE }}
      run: |
        pwd
        git branch
      shell: bash

    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: "v3.9.0"

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.AZURE_CREDENTIALS }}

    - name: Get Creds to AKS Cluster 🔑
      run: |
        az aks get-credentials --resource-group ${{ inputs.RG_NAME }} --name ${{ inputs.CLUSTER_NAME }} --admin
      shell: bash

    - name: Login to ACR
      run: |
        az acr login --name ${{ inputs.ACR_ADDR }}
      shell: bash

    - name: Deploy via Helm Upgrade
      working-directory: _k8s/${{ inputs.HELM_PATH }}/charts/
      run: |
        helm pull oci://${{ inputs.ACR_ADDR }}/helm/${{ inputs.HELM_PATH }} --version ${{ inputs.CHART_VERSION }} --untar

        helm upgrade ${{ inputs.HELM_PATH }} charts/${{ inputs.HELM_PATH }} \
          --debug \
          --install \
          -n ${{ inputs.NAMESPACE }} \
          -f charts/${{ inputs.HELM_PATH }}/values-${{ inputs.ENV }}.yaml \
          --atomic \
          --cleanup-on-fail \
          --wait \
          --set namespace=${{ inputs.NAMESPACE }}
      shell: bash