name: "Build Application 🚧"
description: "Building Frontend Applications"

inputs:
  app-directory:
    description: "App Name"
    required: true

  node-version:
    description: "Node Version"
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Dependencies for ${{ inputs.app-directory }}
      working-directory: "${{ inputs.app-directory }}"
      run: yarn install --frozen-lockfile
      shell: bash

    - name: Build Application using Yarn
      working-directory: "${{ inputs.app-directory }}"
      run:
        |
          yarn build
          yarn build-storybook
          pwd
          ls -lart
      shell: bash
