name: Reusable Build & Deploy Workflow For Frontend

on:
  workflow_call:
    inputs:
      APP_NAME:
        description: "App Name"
        required: true
        type: string
      APP_DIR:
        description: "App Directory"
        required: true
        type: string
      IMAGE_NAME:
        description: "Image Name"
        required: true
        type: string
      IMAGE_TAG:
        description: "Image Tag"
        required: true
        type: string
      LOGIN_SERVER:
        description: "Docker Login Server"
        required: true
        type: string
      DOCKER_LOGIN_USERNAME:
        description: "Docker Login Username"
        required: true
        type: string
      DOCKER_LOGIN_PASS:
        description: "Docker Login Password"
        required: true
        type: string
      NODE_VERSION:
        description: "Node Version"
        required: true
        type: string
      REACT_APP_API_URL:
        description: "Backend API URL"
        required: false
        type: string
      REACT_APP_ENTERPRISE_API_URL:
        description: "Backend Enterprise API URL"
        required: false
        type: string
      REACT_APP_FILE_URL:
        description: "Backend API URL"
        required: false
        type: string
      REACT_APP_IMAGE_URL:
        description: "Backend API URL"
        required: false
        type: string
      REACT_APP_MAIL_URL:
        description: "Backend API URL"
        required: false
        type: string
    secrets:
      REACT_APP_RAZORPAY_KEY_ID:
        description: "Razorpay Key ID"
        required: false
      AZURE_CREDENTIALS:
        description: "Azure Creds"
        required: true
        
jobs:

  setup-version:
    name: "Setup Node Version"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.NODE_VERSION }}

  app-build-frontend:
    needs: [setup-version]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: qwikskills/reusable-workflows/.github/actions/build_frontend_image@main
      with:
        NODE_VERSION: ${{ inputs.NODE_VERSION }}
        LOGIN_SERVER: ${{ inputs.LOGIN_SERVER }}
        DOCKER_LOGIN_USERNAME: ${{ inputs.DOCKER_LOGIN_USERNAME }}
        DOCKER_LOGIN_PASS:  ${{ inputs.DOCKER_LOGIN_PASS }}
        APP_NAME: ${{ inputs.APP_NAME }}
        APP_DIR: ${{ inputs.APP_DIR }}
        IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
        IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
        REACT_APP_API_URL: ${{ inputs.REACT_APP_API_URL }}
        REACT_APP_ENTERPRISE_API_URL: ${{ inputs.REACT_APP_ENTERPRISE_API_URL }}
        REACT_APP_FILE_URL: ${{ inputs.REACT_FILE_URL }}
        REACT_APP_IMAGE_URL: ${{ inputs.REACT_IMAGE_URL }}
        REACT_APP_MAIL_URL: ${{ inputs.REACT_MAIL_URL }}
        REACT_APP_RAZORPAY_KEY_ID: ${{ secrets.REACT_APP_RAZORPAY_KEY_ID }}

  app-deploy-frontend:
    needs: [setup-version, "app-build-frontend"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: qwikskills/reusable-workflows/.github/actions/deploy@main
      with:
        NODE_VERSION: ${{ inputs.NODE_VERSION }}
        LOGIN_SERVER: ${{ inputs.LOGIN_SERVER }}
        DOCKER_LOGIN_USERNAME: ${{ inputs.DOCKER_LOGIN_USERNAME }}
        DOCKER_LOGIN_PASS:  ${{ inputs.DOCKER_LOGIN_PASS }}
        APP_NAME: ${{ inputs.APP_NAME }}
        APP_DIR: ${{ inputs.APP_DIR }}
        IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
        IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
