name: Reusable Build & Deploy Workflow For Frontend

on:
  workflow_call:
    inputs:
      APP_NAME:
        description: "App Name"
        required: true
        type: string
      APP_DIR:
        description: "App Directory"
        required: true
        type: string
      IMAGE_NAME:
        description: "Image Name"
        required: true
        type: string
      IMAGE_TAG:
        description: "Image Tag"
        required: true
        type: string
      LOGIN_SERVER:
        description: "Docker Login Server"
        required: true
        type: string
      DOCKER_LOGIN_USERNAME:
        description: "Docker Login Username"
        required: true
        type: string
      DOCKER_LOGIN_PASS:
        description: "Docker Login Password"
        required: true
        type: string
      NODE_VERSION:
        description: "Node Version"
        required: true
        type: string
      API_URL:
        description: "Backend API URL"
        required: false
        type: string
      ENTERPRISE_API_URL:
        description: "Backend Enterprise API URL"
        required: false
        type: string
      IMAGE_FILE_URL:
        description: "Backend API URL"
        required: false
        type: string
      MAIL_URL:
        description: "Backend API URL"
        required: false
        type: string
      ZIP_CODE_API_ENDPOINT:
        description: "Zipcode API URL"
        required: false
        type: string
    secrets:
      RAZORPAY_KEY_ID_NON_PROD:
        description: "Razorpay Key ID Non Prod"
        required: false
      RAZORPAY_KEY_ID_PROD:
        description: "Razorpay Key ID Prod"
        required: false
      ZIP_CODE_API_KEY:
        description: "Zipcode Key ID"
        required: false
      AZURE_CREDENTIALS:
        description: "Azure Creds"
        required: true
        
jobs:

  setup-version:
    name: "Setup Node Version"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.NODE_VERSION }}

  app-build-frontend:
    needs: [setup-version]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: qwikskills/reusable-workflows/.github/actions/build_frontend_image@main
      with:
        NODE_VERSION: ${{ inputs.NODE_VERSION }}
        LOGIN_SERVER: ${{ inputs.LOGIN_SERVER }}
        DOCKER_LOGIN_USERNAME: ${{ inputs.DOCKER_LOGIN_USERNAME }}
        DOCKER_LOGIN_PASS:  ${{ inputs.DOCKER_LOGIN_PASS }}
        APP_NAME: ${{ inputs.APP_NAME }}
        APP_DIR: ${{ inputs.APP_DIR }}
        IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
        IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
        API_URL: ${{ inputs.API_URL }}
        ENTERPRISE_API_URL: ${{ inputs.ENTERPRISE_API_URL }}
        IMAGE_FILE_URL: ${{ inputs.IMAGE_FILE_URL }}
        MAIL_URL: ${{ inputs.MAIL_URL }}
        ZIP_CODE_API_ENDPOINT: ${{ inputs.ZIP_CODE_API_ENDPOINT }}
        RAZORPAY_KEY_ID_NON_PROD: ${{ secrets.RAZORPAY_KEY_ID_NON_PROD }}
        RAZORPAY_KEY_ID_PROD: ${{ secrets.RAZORPAY_KEY_ID_PROD }}
        ZIP_CODE_API_KEY: ${{ secrets.ZIP_CODE_API_KEY }}

  app-deploy-frontend:
    needs: [setup-version, "app-build-frontend"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: qwikskills/reusable-workflows/.github/actions/deploy@main
      with:
        NODE_VERSION: ${{ inputs.NODE_VERSION }}
        LOGIN_SERVER: ${{ inputs.LOGIN_SERVER }}
        DOCKER_LOGIN_USERNAME: ${{ inputs.DOCKER_LOGIN_USERNAME }}
        DOCKER_LOGIN_PASS:  ${{ inputs.DOCKER_LOGIN_PASS }}
        APP_NAME: ${{ inputs.APP_NAME }}
        APP_DIR: ${{ inputs.APP_DIR }}
        IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
        IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
