name: Reusable Build & Deploy Workflow For Backend

on:
  workflow_call:
    inputs:
      APP_NAME:
        description: "App Name"
        required: true
        type: string
      APP_DIR:
        description: "App Directory"
        required: true
        type: string
      IMAGE_NAME:
        description: "Image Name"
        required: true
        type: string
      IMAGE_TAG:
        description: "Image Tag"
        required: true
        type: string
      JSON_FILE:
        description: "Environment File Name"
        required: false
        type: string
      LOGIN_SERVER:
        description: "Docker Login Server"
        required: true
        type: string
      DOCKER_LOGIN_USERNAME:
        description: "Docker Login Username"
        required: true
        type: string
      DOCKER_LOGIN_PASS:
        description: "Docker Login Password"
        required: true
        type: string
      NODE_VERSION:
        description: "Node Version"
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        description: "Azure Creds"
        required: true

jobs:

  setup-version:
    name: "Setup Node Version"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.NODE_VERSION }}

  app-build-backend:
    needs: [setup-version]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: qwikskills/reusable-workflows/.github/actions/build_backend_image@main
      with:
        NODE_VERSION: ${{ inputs.NODE_VERSION }}
        LOGIN_SERVER: ${{ inputs.LOGIN_SERVER }}
        DOCKER_LOGIN_USERNAME: ${{ inputs.DOCKER_LOGIN_USERNAME }}
        DOCKER_LOGIN_PASS:  ${{ inputs.DOCKER_LOGIN_PASS }}
        APP_NAME: ${{ inputs.APP_NAME }}
        APP_DIR: ${{ inputs.APP_DIR }}
        env: ${{ inputs.env }}
        IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
        IMAGE_TAG: ${{ inputs.IMAGE_TAG }}

  app-deploy-backend:
    needs: [setup-version, "app-build-backend"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: qwikskills/reusable-workflows/.github/actions/deploy@main
      with:
        NODE_VERSION: ${{ inputs.NODE_VERSION }}
        LOGIN_SERVER: ${{ inputs.LOGIN_SERVER }}
        DOCKER_LOGIN_USERNAME: ${{ inputs.DOCKER_LOGIN_USERNAME }}
        DOCKER_LOGIN_PASS:  ${{ inputs.DOCKER_LOGIN_PASS }}
        APP_NAME: ${{ inputs.APP_NAME }}
        APP_DIR: ${{ inputs.APP_DIR }}
        JSON_FILE: ${{ inputs.JSON_FILE }}
        IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
        IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
